### PR TITLE
Added scrolling inventory

### PR DESCRIPTION
**Pull request by m-doescode**
Added an inventory that scrolls to accommodate for more items.

### CODE REVIEW

**Comment by Bluebotlabz** [comment]
wait why was this closed?

**Comment by Bluebotlabz** [comment]
Thank you so much for this btw

**Comment by m-doescode** [comment]
> Thank you so much for this btw

No problem! I'm just glad my code came in handy for someone.

**Comment by Bluebotlabz** [comment]
Forgot to attach Crafti binary
[crafti.tns.zip](https://github.com/Bluebotlaboratories/crafti/files/8762553/crafti.tns.zip)

**Comment by Bluebotlabz** [comment]
Also, it would appear that after placing cyan wool, the bottom inventory row becomes inaccesible

**Comment by Bluebotlabz** [comment]
@m-doescode I've managed to fix the wool changing colours (stupid thing where I copied some code from the lamp renderer), however, the last inventory row is often not scrollable, so the inventory seems to just ignore that row
Basically, try placing something from the last row, then from a different row and it seems to disappear or something (the row, not the block).

Also, here is the binary with the fixed colour but still-broken inventory scrolling
[crafti.tns.zip](https://github.com/Bluebotlaboratories/crafti/files/8762650/crafti.tns.zip)

Thanks again

**Comment by Bluebotlabz** [comment]
The problem seems to be related to the fact that the code doesn't render rows which are not entirely full

**Comment by Bluebotlabz** [comment]
So it seems that if your "cursor" is over a non-existent block, ie: You are on the last block on a row, but the row below isn't full
the inventory refuses to scroll down

**Comment by m-doescode** [comment]
> So it seems that if your "cursor" is over a non-existent block, ie: You are on the last block on a row, but the row below isn't full the inventory refuses to scroll down

Ah, that was intentional, but I see the confusion.

When the last row isn't full.
Ex
```
[] [] [] [] []
[] [] [] [] []
[] [] []
```

If your cursor is in the former half of the row, you will be able to scroll down because there is a block there
Ex.
```
[] [] [] [] []
[]{[]}[] [] []
[] [] []
```

to

```
[] [] [] [] []
[] [] [] [] []
[]{[]}[]
```

BUT if there is NOT a block under it, it will just wrap to the top.
Ex.
```
[] [] [] [] []
[] [] []{[]}[]
[] [] []
```

to

```
[] [] []{[]}[]
[] [] [] [] []
[] [] []
```

Initially, I wanted the next row to show up faded out, but I didn't know how it should look so I gave up.

I could implement it if you'd like

**Comment by Bluebotlabz** [comment]
Yeah
I'm currently trying to figure out your code so that if your cursor is over a non-existent block it kind of just adds one to the current_selection

and something like that when going up

**Comment by m-doescode** [comment]
Ah, maybe instead of scrolling all the way back up, if your cursor enters the last row over a nonexistent block, it goes to the last item on that row.

**Comment by Bluebotlabz** [comment]
yeah, that's basically what I'm trying to do now

**Comment by Bluebotlabz** [comment]
the best part of all this is that I have an Nspire CX II-T

so I can't emulate it making debugging a _little_ harder

**Comment by m-doescode** [comment]
> the best part of all this is that I have an Nspire CX II-T
> 
> so I can't emulate it making debugging a _little_ harder

Why is it not possible to emulate?

**Comment by m-doescode** [comment]
> I seem to be struggling with the implementation of this, how would you propose I should do it?

It would probably be by editing these lines
182,193 @ blocklisttask.cpp
```cpp
    else if (keyPressed(KEY_NSPIRE_2) || keyPressed(KEY_NSPIRE_DOWN))
    {
        // Increment current cell by row size and overflow
        current_selection += fields_x;
        if (current_selection >= user_selectable_count)
            current_selection %= fields_x;
        
        moveScreenOffset();

        key_held_down = true;
    }
```

I'm trying to figure out a way to fix it too, I'll let you know when I get something to work.

**Comment by Bluebotlabz** [comment]
yeah...

this works sort-off:
~~~c++
else if (keyPressed(KEY_NSPIRE_2) || keyPressed(KEY_NSPIRE_DOWN) || keyPressed(KEY_NSPIRE_S))
    {
        // Increment current cell by row size and overflow
        current_selection += fields_x;
        if (current_selection >= user_selectable_count && user_selectable_count - (current_selection+fields_x) != 0) {
            current_selection = user_selectable_count-1;
        }
        else if (current_selection >= user_selectable_count)
            current_selection %= fields_x;
        
        moveScreenOffset();

        key_held_down = true;
    }
~~~

**Comment by Bluebotlabz** [comment]
I just need to figure out how to get it to properlly recognise that it is on the last row so it goes back to the top

**Comment by m-doescode** [comment]
```cpp
else if(keyPressed(KEY_NSPIRE_2) || keyPressed(KEY_NSPIRE_DOWN) || keyPressed(KEY_NSPIRE_S))
    {
        const int rows = ((user_selectable_count + fields_x - 1) / fields_x); 
        // Increment current cell by row size and overflow
        current_selection += fields_x;
        if (current_selection >= user_selectable_count)
        {
            if (current_selection > rows * fields_x)
                current_selection %= fields_x;
            else
                current_selection = user_selectable_count - 1;
        }

        moveScreenOffset();

        key_held_down = true;
    }
```

This code kinda works. But the going up one was not changed, so if you are at the latter half of the first row and press up, you won't go to the last row.

I'm wondering if I can replace the division-remultiplication with std::round in the cmath header.

**Comment by Bluebotlabz** [comment]
wait. there was a rows variable this whole time?
I didn't see that

**Comment by Bluebotlabz** [comment]
I was basically missing a variable to calculate which row I am on and what the total is
I'll send my code in a second

**Comment by Bluebotlabz** [comment]
ok I'm stupid, how can I figure out which row i'm in?

**Comment by m-doescode** [comment]
> ok I'm stupid, how can I figure out which row i'm in?

The row you are at can be determined by

current_selection / fields_x (First row will be 0, second will be 1, and so forth)

Anyways, don't worry about it. I've already submitted a new PR to fix this issue (#10)

**Comment by Bluebotlabz** [comment]
Wait. Why was the PR closed?

**Pull request merged**
