### PR TITLE
Add scrolling inventory

### PR DESCRIPTION
**Pull request by Bluebotlabz**
Thanks to @m-doescode

### CODE REVIEW

**Comment by m-doescode** [comment]
Please do note that there is a lot of other junk that I merged into this branch. I will clean it up in a minute

**Comment by Bluebotlabz** [comment]
My overall plan for this fork is:
- Add speed control for the trackpad
- Maybe change from int to fixed-point to fix graphics problems
- Add every block in the texture atlas to the game (just as a block, I don't currently plan on adding functionality to them)
- Add some additionaly performance settings

**Comment by m-doescode** [comment]
That's alright. Just rollback this merge and I'll submit a pr later

**Comment by m-doescode** [comment]
> Thanks, btw, just wondering, what `other junk` did you add to the repo?

I made a bunch of other branches that would be useful for me when debugging but didn't know how to manage it to so it all wound up merged in one branch. My original plan was to remove them once I was done debugging but I forgot

I added stuff like:
- Seperated output tns file and obj files into another directory for cleanliness
- Added WASD controls for easier debugging

**Comment by Bluebotlabz** [comment]
Actually, despite the fact that I have an nspire CX II-T (no emulator for it)

WASD may be useful as a keyboard _can_ be connected to the calculator

Also, what are the obj files for?
(definitely not an Ndless/C++ noob)

**Comment by m-doescode** [comment]
> Also, what are the obj files for?

Those are a C thing. Basically, when you have multiple files (e.g. main.c block.c test.c) they all get compiled into seperate obj files (e.g. main.o block.o test.o) and then finally, they all get linked together into the binary.

The use case for this is that if you make changes to, say, block.c, and you compile it, you won't have to recompile test.c and main.c too.

> Honestly, I might keep those features, although I may change the mapping for the keyboard

Fine by me, though I would recommend opening a separate PR for that. I will push my branches if you like.

**Comment by m-doescode** [comment]
> Also, with your idea for the implementation of stairs, were you planing on having a custom model for them?

Yes, initially I wanted to add stairs so that my house would look a little less blocky, but eventually I gave up because I didn't want to bother dealing with vertices and whatnot. Feel free to add it yourself if you like.

Oh, and I also got sidetracked into making the scrolling inventory because of it, because if I was going to make one type of stair, why not make all types of stairs? And that wouldn't have been possible in the past.

**Comment by Bluebotlabz** [comment]
I genuinely don't think I can be bothered to figure out all the code required for stairs and stair-related movement and stair-collision thingies, however, blocks that look like stairs may be possible-ish as "transparent" textures are possible, the only problem would be adding the textures to the map as I haven't quite figured out how all the code in that works yet

You work with the scrolling inventory is literally a lifesaver because I'm definitely not a C++ noob who has no idea how to do that

**Comment by m-doescode** [comment]
> I genuinely don't think I can be bothered to figure out all the code required for stairs and stair-related movement and stair-collision thingies, however, blocks that look like stairs may be possible-ish as "transparent" textures are possible, the only problem would be adding the textures to the map as I haven't quite figured out how all the code in that works yet
> 
> You work with the scrolling inventory is literally a lifesaver because I'm definitely not a C++ noob who has no idea how to do that

No problem!

**Comment by m-doescode** [comment]
Also, I see you have reverted the revert, so should I close my new PR now?

**Comment by m-doescode** [comment]
Note that the one you have unreverted was the one that merged master, which doesn't contain the scrolling code.

**Comment by m-doescode** [comment]
> No since the reverted revert is for the master branch which has some debug stuff but doesn't seem to have scrolling

Ah ok, reopened. #8  btw

**Comment by Bluebotlabz** [comment]
> Note that the one you have unreverted was the one that merged master, which doesn't contain the scrolling code.

yeah basically

**Comment by Bluebotlabz** [comment]
> > No since the reverted revert is for the master branch which has some debug stuff but doesn't seem to have scrolling
> 
> Ah ok, reopened. #8 btw

thanks!

**Pull request merged**
